### PR TITLE
Support onChecked and onUnchecked events in the ReactSDK

### PR DESCRIPTION
**Pull request by jasonabrown**
Add support for onChecked and onUnchecked snippet events in the ReactSDK.(https://ironcladapp.atlassian.net/browse/IRON-25322).

## Manual Testing
Verified locally

## Regression Risks
-None

### CODE REVIEW

**Review by mewelling — APPROVED** [review]
@jasonabrown approving, but can you set some time to walk through this with @tstutson so that we can hand off to QE? Alternatively, if we had a loom or something of how it worked i'd be fine with that, too!

**Comment by jasonabrown** [comment]
@mewelling - added a loom to the JIRA.

**Comment by cdhcs1516** [comment]
@jasonabrown thanks for working on this. Could you also update the ReadMe?

**Comment by jasonabrown** [comment]
@cdhcs1516 - I updated the ReadMe.

**Review by cdhcs1516 — APPROVED** [review]
Thanks for resolving this!

**Pull request merged**
